apiVersion: v1
kind: Pod
metadata:
  name: test-db-custom-secret
  namespace: edu-roman-belozerov
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: db-certs
      mountPath: /root/.postgresql/
      readOnly: true
  volumes:
  - name: db-certs
    secret:
      secretName: postgres-ssl-cert
      items:
      - key: root.crt
        path: root.crt
        mode: 0600